#!/usr/bin/env python3
"""Embed web/ static files into a C++ translation unit for judge_engine."""

import pathlib
import sys
import textwrap


def content_type_for(path: str) -> str:
    if path.endswith(".html"):
        return "text/html; charset=utf-8"
    if path.endswith(".css"):
        return "text/css; charset=utf-8"
    if path.endswith(".js"):
        return "application/javascript; charset=utf-8"
    if path.endswith(".json"):
        return "application/json; charset=utf-8"
    return "application/octet-stream"


def format_byte_array(data: bytes, var: str) -> str:
    lines = [f"static const unsigned char {var}[] = {{"]
    row = []
    for i, b in enumerate(data):
        row.append(f"0x{b:02x}")
        if len(row) == 16:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ", ".join(row) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print("Usage: embed_web_assets.py <web_dir> <output.cpp>", file=sys.stderr)
        return 1

    web_dir = pathlib.Path(sys.argv[1])
    output = pathlib.Path(sys.argv[2])

    mappings = [
        ("index.html", "/index.html"),
        ("index.html", "/"),
        ("css/style.css", "/css/style.css"),
        ("js/app.js", "/js/app.js"),
    ]

    blobs = []
    assets = []
    for rel, url_path in mappings:
        src = web_dir / rel
        if not src.is_file():
            print(f"Missing web asset: {src}", file=sys.stderr)
            return 1
        data = src.read_bytes()
        var = f"kAsset_{len(blobs)}"
        blobs.append((var, data))
        assets.append((url_path, content_type_for(rel), var, len(data)))

    parts = [
        "// Auto-generated by judge/tools/embed_web_assets.py. Do not edit.",
        '#include "web_server.h"',
        "",
    ]

    for var, data in blobs:
        parts.append(format_byte_array(data, var))
        parts.append("")

    parts.append("static const EmbeddedAsset kEmbeddedAssets[] = {")
    for url_path, ctype, var, size in assets:
        parts.append(f'  {{ "{url_path}", "{ctype}", {var}, {size} }},')
    parts.append("};")
    parts.append("")
    parts.append("const EmbeddedAsset* embeddedAssetsBegin() {")
    parts.append("  return kEmbeddedAssets;")
    parts.append("}")
    parts.append("")
    parts.append("const EmbeddedAsset* embeddedAssetsEnd() {")
    parts.append(
        "  return kEmbeddedAssets + sizeof(kEmbeddedAssets) / sizeof(kEmbeddedAssets[0]);"
    )
    parts.append("}")
    parts.append("")
    parts.append("const EmbeddedAsset* findEmbeddedAsset(const std::string& url_path) {")
    parts.append(
        "  for (const EmbeddedAsset* it = embeddedAssetsBegin(); it != embeddedAssetsEnd(); ++it) {"
    )
    parts.append("    if (url_path == it->path) {")
    parts.append("      return it;")
    parts.append("    }")
    parts.append("  }")
    parts.append("  return nullptr;")
    parts.append("}")
    parts.append("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(parts), encoding="utf-8")
    print(f"Generated {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
